In [1]:
# NumPy ufuncs :


In [2]:
# What are ufuncs?
# ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [3]:
# Why use ufunncs?
# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

# They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

# ufuncs also take additional arguments, like:

# where boolean array or condition defining where the operations should take place.

# dtype defining the return type of elements.

# out output array where the return value should be copied.

In [4]:
# What is Vectorization? 
# Converting iterative statements into a vector based operation is called vectorization.
# it is faster as modern CPUs are optimised for such operations.

In [5]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [6]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [7]:
# Create Your Own ufunc :
# how to create your own ufunc :
# To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

# The frompyfunc() method takes the following arguments:

# function - the name of the function.
# inputs - the number of input arguments (arrays).
# outputs - the number of output arrays.

In [8]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [9]:
# Check if a Function is a ufunc :
# Check the type of a function to check if it is a ufunc or not.

# A ufunc should return <class 'numpy.ufunc'>.


In [10]:
import numpy as np
print (type(np.add))

<class 'numpy.ufunc'>


In [11]:
import numpy as np

print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [12]:
# Use an if statement to check if the function is a ufunc or not: 
import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [13]:
# Simple Arithmetic :


In [14]:
# Simple Arithmetic :
# Addition :
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [15]:
# Substraction :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [16]:
# Multiiplication :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [17]:
# Division :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [18]:
# Power :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [19]:
# Remainder :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [20]:
# Return the remainders :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [21]:
# Quotient and Mod :
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [22]:
# Absoulute Values :
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [1]:
# Rounding Decimals :


In [2]:
# There are primarily five ways of rounding off decimals in NumPy:

# truncation
# fix
# rounding
# floor
# ceil

In [3]:
# Truncation :
# Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [4]:
import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [5]:
# Rounding :
# The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


In [6]:
# Floor :
# The floor() function rounds off decimal to nearest lower integer.
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [7]:
# Ceil :
# The ceil() function rounds off decimal to nearest upper integer.
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [1]:
# NumPy Logs :


In [2]:
# Logs :
# NumPy provides functions to perform log at the base 2, e and 10.

# We will also explore how we can take log for any base by creating a custom ufunc.

# All of the log functions will place -inf or inf in the elements if the log can not be computed.

In [4]:
# Log at Base 2 :
# Use the log2() function to perform log at the base 2.
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
