In [1]:
# Random Numbers in NumPy :


In [2]:
from numpy import random

x = random.randint(100)

print(x)

80


In [3]:
from numpy import random

x = random.rand()

print(x)

0.07298581427996065


In [4]:
# Generate Random Array :


In [1]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[62 16 66 39 58]


In [2]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[92  9 82 81 28]
 [76 54 17 10 23]
 [49 99 29 98 25]]


In [3]:
# Floats :

In [4]:
from numpy import random

x = random.rand(5)

print(x)

[0.14665816 0.34897528 0.87635647 0.07107675 0.02567066]


In [5]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.91575615 0.40038966 0.53045741 0.23042041 0.14457788]
 [0.49104354 0.10332498 0.97907986 0.89064861 0.47818979]
 [0.968078   0.72960472 0.41816515 0.30745899 0.00365897]]


In [6]:
# Generate Random Number From Array :

In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 7 5 3]
 [5 9 9 3 7]
 [7 7 9 7 5]]


In [1]:
# Data Distribution :

In [2]:
# Random Distribution :
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 5 5 5 7 7 5 7 7 5 7 7 7 7 7 3 5 7 5 7 7 5 5 7 5 5 5 7 7 3 3 3 5 7 5 7
 7 5 3 5 7 7 7 5 5 7 7 7 7 5 7 5 7 3 7 7 7 7 5 5 5 5 7 3 5 7 7 7 7 5 7 7 7
 5 5 7 5 7 7 7 7 5 7 3 7 3 7 3 7 5 7 7 5 3 5 7 5 7 7]


In [4]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 7 7 7 5]
 [3 7 7 5 7]
 [3 7 7 7 7]]
