In [1]:
print("hlo data science")

hlo data science


In [4]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)



NumPy version: 2.3.4
Pandas version: 2.3.3


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr + 10)
print(arr * 2)
print(arr / 5)


[20 30 40 50]
[20 40 60 80]
[2. 4. 6. 8.]


In [1]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30])

print(arr[0:3])     # first 3 elements
print(arr[2:5])     # elements from index 2 to 4
print(arr[-2:])     # last 2 elements


[ 5 10 15]
[15 20 25]
[25 30]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print("Original:", arr)
print("Reshaped:\n", reshaped)


Original: [1 2 3 4 5 6]
Reshaped:
 [[1 2 3]
 [4 5 6]]


In [3]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Kunal"],
    "Age": [21, 24, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df


Name  Age    City
0   Aman   21   Delhi
1   Riya   24  Mumbai
2  Kunal   20    Pune

In [7]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Kunal"],
    "Age": [21, 24, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df.index = df.index + 1  # start index from 1

print(df)
df.head()
df.info()
df.describe()





    Name  Age    City
1   Aman   21   Delhi
2   Riya   24  Mumbai
3  Kunal   20    Pune
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


Age
count   3.000000
mean   21.666667
std     2.081666
min    20.000000
25%    20.500000
50%    21.000000
75%    22.500000
max    24.000000

In [14]:
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Karan", "Sara", "John"],
    "Age": [21, 25, 19, 23, 30],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)
df.head()      # first 5 rows
df.tail()      # last 5 rows


Name  Age  Marks
0   Amit   21     85
1   Riya   25     90
2  Karan   19     78
3   Sara   23     88
4   John   30     92